In [1]:
import numpy as np
import pandas as pd
import sklearn.metrics as sm
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [2]:
ds = pd.read_csv(r"E:\SmartInternz_Pynb\bank.csv")
ds

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,deposit
0,59,admin.,married,secondary,no,2343,yes,no,unknown,5,may,1042,1,-1,0,unknown,yes
1,56,admin.,married,secondary,no,45,no,no,unknown,5,may,1467,1,-1,0,unknown,yes
2,41,technician,married,secondary,no,1270,yes,no,unknown,5,may,1389,1,-1,0,unknown,yes
3,55,services,married,secondary,no,2476,yes,no,unknown,5,may,579,1,-1,0,unknown,yes
4,54,admin.,married,tertiary,no,184,no,no,unknown,5,may,673,2,-1,0,unknown,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11157,33,blue-collar,single,primary,no,1,yes,no,cellular,20,apr,257,1,-1,0,unknown,no
11158,39,services,married,secondary,no,733,no,no,unknown,16,jun,83,4,-1,0,unknown,no
11159,32,technician,single,secondary,no,29,no,no,cellular,19,aug,156,2,-1,0,unknown,no
11160,43,technician,married,secondary,no,0,no,yes,cellular,8,may,9,2,172,5,failure,no
11161,34,technician,married,secondary,no,0,no,no,cellular,9,jul,628,1,-1,0,unknown,no

In [3]:
ds.isnull().any()

age          False
job          False
marital      False
education    False
default      False
balance      False
housing      False
loan         False
contact      False
day          False
month        False
duration     False
campaign     False
pdays        False
previous     False
poutcome     False
deposit      False
dtype: bool

In [4]:
ds.isnull().sum()

age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
deposit      0
dtype: int64

In [5]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11162 entries, 0 to 11161
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        11162 non-null  int64
 1   job        11162 non-null  object
 2   marital    11162 non-null  object
 3   education  11162 non-null  object
 4   default    11162 non-null  object
 5   balance    11162 non-null  int64
 6   housing    11162 non-null  object
 7   loan       11162 non-null  object
 8   contact    11162 non-null  object
 9   day        11162 non-null  int64
 10  month      11162 non-null  object
 11  duration   11162 non-null  int64
 12  campaign   11162 non-null  int64
 13  pdays      11162 non-null  int64
 14  previous   11162 non-null  int64
 15  poutcome   11162 non-null  object
 16  deposit    11162 non-null  object
dtypes: int64(7), object(10)
memory usage: 1.4+ MB

In [6]:
ds.describe()

,age,balance,day,duration,campaign,pdays,previous
count,11162.000000,11162.000000,11162.000000,11162.000000,11162.000000,11162.000000,11162.000000
mean,41.231948,1528.538524,15.658036,371.993818,2.508421,51.330407,0.832557
std,11.913369,3225.413326,8.420740,347.128386,2.722077,108.758282,2.292007
min,18.000000,-6847.000000,1.000000,2.000000,1.000000,-1.000000,0.000000
25%,32.000000,122.000000,8.000000,138.000000,1.000000,-1.000000,0.000000
50%,39.000000,550.000000,15.000000,255.000000,2.000000,-1.000000,0.000000
75%,49.000000,1708.000000,22.000000,496.000000,3.000000,20.750000,1.000000
max,95.000000,81204.000000,31.000000,3881.000000,63.000000,854.000000,58.000000

In [7]:
x = ds.iloc[:, :-1].values
y = ds.iloc[:, 16].values

In [8]:
ct = ColumnTransformer([("one",OneHotEncoder(),[1,2,3,4,6,7,8,10,15])],remainder = "passthrough")
x = ct.fit_transform(x)

In [9]:
x

array([[1.0, 0.0, 0.0, ..., 1, -1, 0],
       [1.0, 0.0, 0.0, ..., 1, -1, 0],
       [0.0, 0.0, 0.0, ..., 1, -1, 0],
       ...,
       [0.0, 0.0, 0.0, ..., 2, -1, 0],
       [0.0, 0.0, 0.0, ..., 2, 172, 5],
       [0.0, 0.0, 0.0, ..., 1, -1, 0]], dtype=object)

In [10]:
y = ds.deposit.replace(to_replace=['no', 'yes'], value=[0, 1])

In [11]:
y

0        1
1        1
2        1
3        1
4        1
        ..
11157    0
11158    0
11159    0
11160    0
11161    0
Name: deposit, Length: 11162, dtype: int64

In [12]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [13]:
x_train.shape

(8929, 51)

In [14]:
y_train.shape

(8929,)

In [15]:
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [16]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
reg=Sequential()
reg.add(Dense(units=17,kernel_initializer= "random_uniform",activation= "relu"))
reg.add(Dense(units=34,kernel_initializer= "random_uniform",activation= "relu"))
reg.add(Dense(units=34,kernel_initializer= "random_uniform",activation= "relu"))
reg.add(Dense(units=34,kernel_initializer= "random_uniform",activation= "relu"))
reg.add(Dense(units=34,kernel_initializer= "random_uniform",activation= "relu"))
reg.add(Dense(units=34,kernel_initializer= "random_uniform",activation= "relu"))
reg.add(Dense(units=1,kernel_initializer= "random_uniform",activation= "relu"))
reg.compile(optimizer="rmsprop",loss="mean_squared_error",metrics=["accuracy"])

In [17]:
reg.fit(x_train,y_train,epochs=100)

Epoch 1/100
280/280 [==============================] - 1s 935us/step - loss: 0.1896 - accuracy: 0.7522
Epoch 2/100
280/280 [==============================] - 0s 926us/step - loss: 0.1408 - accuracy: 0.8163
Epoch 3/100
280/280 [==============================] - 0s 924us/step - loss: 0.1265 - accuracy: 0.8388
Epoch 4/100
280/280 [==============================] - 0s 916us/step - loss: 0.1160 - accuracy: 0.8491
Epoch 5/100
280/280 [==============================] - 0s 910us/step - loss: 0.1111 - accuracy: 0.8562
Epoch 6/100
280/280 [==============================] - 0s 924us/step - loss: 0.1088 - accuracy: 0.8536
Epoch 7/100
280/280 [==============================] - 0s 2ms/step - loss: 0.1067 - accuracy: 0.8607
Epoch 8/100
280/280 [==============================] - 1s 2ms/step - loss: 0.1059 - accuracy: 0.8599
Epoch 9/100
280/280 [==============================] - 1s 2ms/step - loss: 0.1046 - accuracy: 0.8634
Epoch 10/100
280/280 [==============================] - 1s 2ms/step - loss: 0.1035 - accuracy: 0.8642
Epoch 11/100
280/280 [==============================] - 1s 2ms/step - loss: 0.1027 - accuracy: 0.8674
Epoch 12/100
280/280 [==============================] - 1s 2ms/step - loss: 0.1024 - accuracy: 0.8643
Epoch 13/100
280/280 [==============================] - 1s 2ms/step - loss: 0.1011 - accuracy: 0.8694
Epoch 14/100
280/280 [==============================] - 1s 2ms/step - loss: 0.1007 - accuracy: 0.8703: 0s - loss: 0.103
Epoch 15/100
280/280 [==============================] - 1s 2ms/step - loss: 0.1001 - accuracy: 0.8682
Epoch 16/100
280/280 [==============================] - 1s 2ms/step - loss: 0.0992 - accuracy: 0.8701
Epoch 17/100
280/280 [==============================] - 1s 2ms/step - loss: 0.0983 - accuracy: 0.8736
Epoch 18/100
280/280 [==============================] - 1s 2ms/step - loss: 0.0981 - accuracy: 0.8714
Epoch 19/100
280/280 [==============================] - 1s 2ms/step - loss: 0.0971 - accuracy: 0.8703
Epoch 20/100
280/280 [==============================] - 1s 2ms/step - loss: 0.0955 - accuracy: 0.8762: 0s - loss: 0.0953 - accuracy: 0.87
Epoch 21/100
280/280 [==============================] - 1s 2ms/step - loss: 0.0950 - accuracy: 0.8805
Epoch 22/100
280/280 [==============================] - 1s 2ms/step - loss: 0.0934 - accuracy: 0.8795
Epoch 23/100
280/280 [==============================] - 1s 2ms/step - loss: 0.0935 - accuracy: 0.8798
Epoch 24/100
280/280 [==============================] - 1s 2ms/step - loss: 0.0932 - accuracy: 0.8799
Epoch 25/100
280/280 [==============================] - 1s 2ms/step - loss: 0.0920 - accuracy: 0.8822
Epoch 26/100
280/280 [==============================] - 1s 2ms/step - loss: 0.0918 - accuracy: 0.8826
Epoch 27/100
280/280 [==============================] - 1s 2ms/step - loss: 0.0907 - accuracy: 0.8831
Epoch 28/100
280/280 [==============================] - 1s 2ms/step - loss: 0.0902 - accuracy: 0.8833
Epoch 29/100
280/280 [==============================] - 1s 2ms/step - loss: 0.0898 - accuracy: 0.8852
Epoch 30/100
280/280 [==============================] - 1s 2ms/step - loss: 0.0893 - accuracy: 0.8874
Epoch 31/100
280/280 [==============================] - 1s 2ms/step - loss: 0.0878 - accuracy: 0.8880
Epoch 32/100
280/280 [==============================] - 1s 2ms/step - loss: 0.0872 - accuracy: 0.8900
Epoch 33/100
280/280 [==============================] - 1s 2ms/step - loss: 0.0870 - accuracy: 0.8911
Epoch 34/100
280/280 [==============================] - 1s 2ms/step - loss: 0.0864 - accuracy: 0.8929
Epoch 35/100
280/280 [==============================] - 1s 2ms/step - loss: 0.0854 - accuracy: 0.8948
Epoch 36/100
280/280 [==============================] - 1s 2ms/step - loss: 0.0857 - accuracy: 0.8899
Epoch 37/100
280/280 [==============================] - 1s 2ms/step - loss: 0.0850 - accuracy: 0.8933
Epoch 38/100
280/280 [==============================] - 1s 2ms/step - loss: 0.0846 - accuracy: 0.8932
Epoch 39/100
280/280 [==============================] - 1s 2ms/step - loss: 0.0843 - accuracy: 0.8960
Epoch 40/100
280/280 [==============================] - 1s 2ms/step - loss: 0.0830 - accuracy: 0.8963
Epoch 41/100
280/280 [==============================] - 1s 2ms/step - loss: 0.0831 - accuracy: 0.8952
Epoch 42/100
280/280 [==============================] - 1s 2ms/step - loss: 0.0819 - accuracy: 0.8985
Epoch 43/100
280/280 [==============================] - 1s 2ms/step - loss: 0.0825 - accuracy: 0.8961
Epoch 44/100
280/280 [==============================] - 1s 2ms/step - loss: 0.0818 - accuracy: 0.8982
Epoch 45/100
280/280 [==============================] - 1s 2ms/step - loss: 0.0810 - accuracy: 0.9007
Epoch 46/100
280/280 [==============================] - 1s 2ms/step - loss: 0.0806 - accuracy: 0.9009
Epoch 47/100
280/280 [==============================] - 1s 2ms/step - loss: 0.0792 - accuracy: 0.9028
Epoch 48/100
280/280 [==============================] - 1s 2ms/step - loss: 0.0801 - accuracy: 0.9012
Epoch 49/100
280/280 [==============================] - 1s 2ms/step - loss: 0.0790 - accuracy: 0.9020
Epoch 50/100
280/280 [==============================] - 1s 2ms/step - loss: 0.0778 - accuracy: 0.9033
Epoch 51/100
280/280 [==============================] - 1s 2ms/step - loss: 0.0786 - accuracy: 0.9023
Epoch 52/100
280/280 [==============================] - 1s 2ms/step - loss: 0.0781 - accuracy: 0.9038
Epoch 53/100
280/280 [==============================] - 1s 2ms/step - loss: 0.0777 - accuracy: 0.9036
Epoch 54/100
280/280 [==============================] - 1s 2ms/step - loss: 0.0781 - accuracy: 0.9035
Epoch 55/100
280/280 [==============================] - 1s 2ms/step - loss: 0.0772 - accuracy: 0.9050
Epoch 56/100
280/280 [==============================] - 1s 2ms/step - loss: 0.0768 - accuracy: 0.9057
Epoch 57/100
280/280 [==============================] - 1s 2ms/step - loss: 0.0768 - accuracy: 0.9053
Epoch 58/100
280/280 [==============================] - 1s 2ms/step - loss: 0.0758 - accuracy: 0.9075
Epoch 59/100
280/280 [==============================] - 1s 2ms/step - loss: 0.0757 - accuracy: 0.9074
Epoch 60/100
280/280 [==============================] - 1s 2ms/step - loss: 0.0752 - accuracy: 0.9075
Epoch 61/100
280/280 [==============================] - 1s 2ms/step - loss: 0.0756 - accuracy: 0.9083
Epoch 62/100
280/280 [==============================] - 1s 2ms/step - loss: 0.0752 - accuracy: 0.9082
Epoch 63/100
280/280 [==============================] - 1s 2ms/step - loss: 0.0752 - accuracy: 0.9092
Epoch 64/100
280/280 [==============================] - 1s 2ms/step - loss: 0.0735 - accuracy: 0.9113
Epoch 65/100
280/280 [==============================] - 1s 2ms/step - loss: 0.0749 - accuracy: 0.9074
Epoch 66/100
280/280 [==============================] - 1s 2ms/step - loss: 0.0740 - accuracy: 0.9106
Epoch 67/100
280/280 [==============================] - 1s 2ms/step - loss: 0.0733 - accuracy: 0.9105: 0s - loss: 0.0698 - accu
Epoch 68/100
280/280 [==============================] - 1s 2ms/step - loss: 0.0739 - accuracy: 0.9114
Epoch 69/100
280/280 [==============================] - 1s 2ms/step - loss: 0.0730 - accuracy: 0.9117
Epoch 70/100
280/280 [==============================] - 1s 2ms/step - loss: 0.0722 - accuracy: 0.9115
Epoch 71/100
280/280 [==============================] - 1s 2ms/step - loss: 0.0727 - accuracy: 0.9098
Epoch 72/100
280/280 [==============================] - 1s 2ms/step - loss: 0.0722 - accuracy: 0.9126
Epoch 73/100
280/280 [==============================] - 1s 2ms/step - loss: 0.0732 - accuracy: 0.9095
Epoch 74/100
280/280 [==============================] - 1s 2ms/step - loss: 0.0712 - accuracy: 0.9125
Epoch 75/100
280/280 [==============================] - 1s 2ms/step - loss: 0.0719 - accuracy: 0.9132
Epoch 76/100
280/280 [==============================] - 1s 2ms/step - loss: 0.0716 - accuracy: 0.9130
Epoch 77/100
280/280 [==============================] - 1s 2ms/step - loss: 0.0710 - accuracy: 0.9148
Epoch 78/100
280/280 [==============================] - 1s 2ms/step - loss: 0.0713 - accuracy: 0.9126
Epoch 79/100
280/280 [==============================] - 1s 2ms/step - loss: 0.0711 - accuracy: 0.9140
Epoch 80/100

280/280 [==============================] - 1s 2ms/step - loss: 0.0706 - accuracy: 0.9141
Epoch 81/100
280/280 [==============================] - 1s 2ms/step - loss: 0.0708 - accuracy: 0.9147
Epoch 82/100
280/280 [==============================] - 1s 2ms/step - loss: 0.0715 - accuracy: 0.9140
Epoch 83/100
280/280 [==============================] - 1s 2ms/step - loss: 0.0702 - accuracy: 0.9132
Epoch 84/100
280/280 [==============================] - 1s 2ms/step - loss: 0.0704 - accuracy: 0.9148
Epoch 85/100
280/280 [==============================] - 1s 2ms/step - loss: 0.0691 - accuracy: 0.9161
Epoch 86/100
280/280 [==============================] - 1s 2ms/step - loss: 0.0690 - accuracy: 0.9160
Epoch 87/100
280/280 [==============================] - 1s 2ms/step - loss: 0.0694 - accuracy: 0.9149
Epoch 88/100
280/280 [==============================] - 1s 2ms/step - loss: 0.0690 - accuracy: 0.9168
Epoch 89/100
280/280 [==============================] - 1s 2ms/step - loss: 0.0681 - accuracy: 0.9180
Epoch 90/100
280/280 [==============================] - 1s 2ms/step - loss: 0.0685 - accuracy: 0.9169
Epoch 91/100
280/280 [==============================] - 1s 2ms/step - loss: 0.0677 - accuracy: 0.9193
Epoch 92/100
280/280 [==============================] - 1s 2ms/step - loss: 0.0674 - accuracy: 0.9190
Epoch 93/100
280/280 [==============================] - 1s 2ms/step - loss: 0.0670 - accuracy: 0.9205
Epoch 94/100
280/280 [==============================] - 1s 2ms/step - loss: 0.0674 - accuracy: 0.9188
Epoch 95/100
280/280 [==============================] - 1s 2ms/step - loss: 0.0672 - accuracy: 0.9201
Epoch 96/100
280/280 [==============================] - 1s 2ms/step - loss: 0.0659 - accuracy: 0.9210
Epoch 97/100
280/280 [==============================] - 1s 2ms/step - loss: 0.0655 - accuracy: 0.9229
Epoch 98/100
280/280 [==============================] - 1s 2ms/step - loss: 0.0659 - accuracy: 0.9223
Epoch 99/100
280/280 [==============================] - 1s 2ms/step - loss: 0.0664 - accuracy: 0.9217
Epoch 100/100
280/280 [==============================] - 1s 2ms/step - loss: 0.0659 - accuracy: 0.9219

In [18]:
ypred = reg.predict(x_test)
ypred

array([[0.       ],
       [1.0093318],
       [0.       ],
       ...,
       [0.9716648],
       [0.       ],
       [0.       ]], dtype=float32)

In [19]:
y_test

9058    0
3279    1
6502    0
9327    0
9965    0
       ..
6003    0
5606    0
4808    1
3697    1
9952    0
Name: deposit, Length: 2233, dtype: int64